package it.nexi.softpos_evo_kotlin_01.services

import it.nexi.softpos_evo_kotlin_01.domain.RequestURI
import it.nexi.softpos_evo_kotlin_01.services.SDKNexiService.gson
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.net.HttpURLConnection
import java.net.URL

/**
 *
 * Nexi Payment
 *
 * Some functionalities must be implemented at the
 * backend level by the client.
 * References are provided as examples.
 *
 */
object BackendService {

    /**
     *
     * Example of the method used to receive
     * the requesturi from Nexi servers.
     *
     * Please note that the deviceId is generated by the SDK;
     * do not confuse it with the Android operating system's device ID.
     *
     */
    suspend fun getRequestUri(deviceId: String): String {

        return withContext(Dispatchers.IO) {

            var connection: HttpURLConnection? = null

            try {

                // The backend web address.
                val strUrlBackend = "http://<yoursite>"

                val url = URL(strUrlBackend)

                connection = url.openConnection() as HttpURLConnection

                connection.apply {

                    requestMethod = "GET"
                    setRequestProperty("Accept", "application/json")
                    doInput = true
                    // connectTimeout = 30000
                    // readTimeout = 30000

                }

                val responseJson = connection.inputStream.bufferedReader().use { it.readText() }

                val responseObj = gson.fromJson(responseJson, RequestURI::class.java)

                responseObj.requestUri

            } catch (ex: Exception) {

                if (connection != null) {
                    try {

                        val responseCode = connection.responseCode

                        val errorStream = connection.errorStream?.bufferedReader()?.use { it.readText() }

                        if (!errorStream.isNullOrEmpty()) {

                        }
                    } catch (ioEx: Exception) {

                    }
                }

                throw Exception(ex.message)

            } finally {

                connection?.disconnect()
            }

        } // return

    } // suspend fun getRequestUri.....

} // end object