package it.nexi.softpos_evo_kotlin_01.services

import android.app.Activity
import android.util.Log
import com.google.gson.Gson
import it.nexi.softpos_evo_kotlin_01.commons.LoadingDialog
import it.nexi.softpos_evo_kotlin_01.commons.formatA2AError
import it.nexi.softpos_evo_kotlin_01.domain.Constant
import it.nexi.softpos_evo_kotlin_01.domain.OperationResult
import it.nexipos.app2app.App2AppIPC
import it.nexipos.app2app.data.model.A2ASDKResponse
import it.nexipos.app2app.data.model.AppData
import it.nexipos.app2app.data.model.CloseAccountData
import it.nexipos.app2app.data.model.ConnectionEvent
import it.nexipos.app2app.data.model.GetLastTransactionData
import it.nexipos.app2app.data.model.PaymentData
import it.nexipos.app2app.data.model.ReversalData
import it.nexipos.app2app.listener.OperationListener
import it.nexipos.app2app.utility.App2AppDomain
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 *
 * Nexi Payment
 *
 * The object provides methods for interfacing with the Nexi SDK.
 * It also allows connected activities to be notified
 * of the outcome of operations performed by the Nexi POS.
 *
 */

object SDKNexiService {

    // LiveData for communicating with Activities in a "lifecycle-aware" manner.
    private val _operationResult = MutableStateFlow<OperationResult?>(null)

    // Public read-only version
    val operationResult: StateFlow<OperationResult?> = _operationResult

    // Method to reset the state
    fun resetResult() {
        _operationResult.value = null
    }

    // Nexi SDK Instance
    lateinit var app2AppIPC: App2AppIPC
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main)
    val gson = Gson()

    /**
     *
     * Starts the SDK initialization.
     * The result will be sent via the 'operationResult' LiveData.
     *
     */
    fun initSDK(
        activity: Activity,
        clientId: String,
        idPuntoVendita: String,
        merchantUserName: String,
        redirectUri: String,
        domain: App2AppDomain,
        deepLinkScheme: String,
        onResult: (Boolean, String?) -> Unit
    ) {
        scope.launch {

            try {

                val appData = withContext(Dispatchers.IO) {
                    getAppData(
                        clientId,
                        redirectUri,
                        idPuntoVendita,
                        merchantUserName,
                        deepLinkScheme,
                        domain
                    )
                }

                app2AppIPC = App2AppIPC(
                    activity,
                    appData,
                    { deviceId, onSuccess, onError ->

                        scope.launch {

                            try {

                                // Please note that the deviceId is generated by the SDK;
                                // do not confuse it with the Android operating system's device ID.

                                LoadingDialog.show(activity)

                                Log.d(Constant.TAG_SOFTPOS_EVO_KOTLIN, "Initiating backend communication – requestUri")

                                // request_uri, request to backend
                                val requestUri = BackendService.getRequestUri(deviceId = deviceId)

                                LoadingDialog.hide()

                                Log.d(Constant.TAG_SOFTPOS_EVO_KOTLIN, "result requestUri: $requestUri")

                                if (!requestUri.isNullOrEmpty()) {

                                    // the request_uri was returned by the backend.
                                    // The request_uri is passed to the SDK for authentication.
                                    onSuccess(requestUri)

                                    // update the LiveData
                                    onResult(true, "The requestUri was returned. : $requestUri")

                                } else {


                                    // The request_uri was not returned by the backend.
                                    // The SDK is notified.
                                    onError("requestUri not found")

                                    // update the LiveData
                                    onResult(false, "Error : request_uri not found")

                                }

                            } catch (e: Exception) {

                                // An error occurred while retrieving the request_uri.
                                // The SDK is notified.
                                onError(e.message ?: "Errore rete")

                                // update the LiveData
                                onResult(false, "An error occurred while retrieving the request_uri.")

                            } // try/catch

                        } // scope launch

                    },
                    { connectionEvent ->

                        scope.launch {

                            // After executing the connectToRemoteService() method
                            // (see later in the code),
                            // the SDK returns the connection status.

                            Log.d(Constant.TAG_SOFTPOS_EVO_KOTLIN, "onConnectionEvent : ${connectionEvent.type}")

                            when (connectionEvent.type) {

                                ConnectionEvent.EventType.READY -> {

                                    Log.d(
                                        Constant.TAG_SOFTPOS_EVO_KOTLIN,
                                        "READY"

                                    )

                                    // Notifies the connected activity that the SDK is READY.
                                    onResult(true, "READY")

                                }

                                ConnectionEvent.EventType.ERROR_APP_NOT_INSTALLED,
                                ConnectionEvent.EventType.ERROR_MULTIPLE_APPS_INSTALLED,
                                ConnectionEvent.EventType.ERROR_GENERIC -> {

                                    // Notifies Error
                                    onResult(false, "Error SDK: ${connectionEvent.type}")

                                }

                                ConnectionEvent.EventType.DISCONNECTED -> {

                                    // Notifies the connected activity that the SDK is disconnected
                                    onResult(false, "Service disconnected")

                                }

                                ConnectionEvent.EventType.CONNECTED -> {

                                    // Notifies the connected activity that che SDK is CONNECTED but not READY
                                    onResult(false, "CONNECTED but not READY")

                                }

                                else -> {

                                    Log.d(
                                        Constant.TAG_SOFTPOS_EVO_KOTLIN,
                                        "unhandled event: ${connectionEvent.type}"
                                    )

                                    // Notifies the connected activity that che SDK
                                    onResult(false, "unhandled event")

                                } // else

                            } // when (connectionEvent.type) {

                        } // scope launch

                    } // onConnectedEvent

                ) // app2AppIPC = App2AppIPC(

                Log.d(Constant.TAG_SOFTPOS_EVO_KOTLIN, "connectToRemoteService")

                // starts the connection with the SDK.
                // The outcome of the operation can be checked in the ConnectionEvent.
                app2AppIPC?.connectToRemoteService()

            } catch (ex: Exception) {

                onResult(false, ex.message ?: "Errore initSDK")

            }

        } // scope.launch

    } // func initSDK

    /**
     *
     * Starts the SDK's Payment method.
     *
     * @param data
     *
     */
    suspend fun executePay(data: PaymentData) {

        try {

            app2AppIPC.pay(data, object : OperationListener {

                    override fun onSuccess(response: A2ASDKResponse?) {

                        // The operation was successful.
                        Log.d(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.pay-> onSuccess() : ${response}")

                        // Send the operation result
                        _operationResult.value = OperationResult(isSuccess = true,
                                                                 description = "Payment -> onSuccess()"
                                                                )

                    } //  override fun onSuccess(response: A2ASDKResponse?) {

                    override fun onFailure(error: A2ASDKResponse?) {

                        // The operation had a negative outcome.
                        val errorMessage = formatA2AError(error)

                        Log.e(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.pay -> onFailure() : ${errorMessage}")

                        // Send the operation result
                        _operationResult.value = OperationResult(isSuccess = false,
                                                                 description = "Payment -> onFailure : ${errorMessage}"
                                                                )

                    } // override fun onFailure(error: A2ASDKResponse?) {

                } // OperationListener

            ) // app2AppIPC.pay(

        } catch (e: Exception) {

            Log.e(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.pay -> exception : ${e.message}")

            _operationResult.value = OperationResult(isSuccess = false,
                                                     description = "Payment -> exception : ${e.message}"
                                                    )

        }

    } //  suspend fun executePay(data: PaymentData): SDKResult {

    /**
     *
     * Starts the SDK's Revert method.
     *
     * @param data
     *
     */
    suspend fun executeRevert(data: ReversalData) {

        try {

            app2AppIPC.revert(data, object : OperationListener {

                    override fun onSuccess(response: A2ASDKResponse?) {

                        // The operation was successful.
                        Log.d(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.revert-> onSuccess() : ${response}")

                        // Send the operation result
                        _operationResult.value = OperationResult(isSuccess = true,
                                                                 description = "Revert -> onSuccess()"
                                                                )

                    } // override fun onSuccess(response: A2ASDKResponse?)

                    override fun onFailure(error: A2ASDKResponse?) {

                        // The operation had a negative outcome.
                        val messaggioErrore = formatA2AError(error)

                        Log.e(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.revert -> onFailure() : ${messaggioErrore}")

                        // Send the operation result
                        _operationResult.value = OperationResult(isSuccess = false,
                                                                 description = "Revert -> onFailure : ${messaggioErrore}"
                                                                )

                    } // override fun onFailure(error: A2ASDKResponse?)

                } // OperationListener

            ) // app2AppIPC.revert

        } catch (e: Exception) {

            Log.e(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.revert -> exception : ${e.message}")

            // Send the operation result
            _operationResult.value = OperationResult(isSuccess = false,
                                                     description = "Payment -> exception : ${e.message}"
                                                    )

        }

    } // suspend fun executeRevert(data: ReversalData): SDKResult {

    /**
     *
     * Starts the SDK's GetLastTransaction method.
     *
     * @param data
     *
     */
    suspend fun executeGetLastTransaction(data: GetLastTransactionData) {

        try {

            app2AppIPC.getLastTransaction(data, object : OperationListener {

                    override fun onSuccess(response: A2ASDKResponse?) {

                        // The operation was successful.
                        Log.d(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.getLastTransaction-> onSuccess() : ${response}")

                        // Send the operation result
                        _operationResult.value = OperationResult(isSuccess = true,
                                                                 description = "GetLastTransaction -> onSuccess()"
                                                                )

                    } //  override fun onSuccess(response: A2ASDKResponse?)

                    override fun onFailure(error: A2ASDKResponse?) {

                        // The operation had a negative outcome.
                        val errorMessage = formatA2AError(error)

                        Log.e(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.GetLastTransaction -> onFailure() : ${errorMessage}")

                        // Send the operation result
                        _operationResult.value = OperationResult(isSuccess = false,
                                                                 description = "GetLastTransaction -> onFailure : ${errorMessage}"
                                                                )

                    } //  override fun onFailure(error: A2ASDKResponse?)

                } // OperationListener

            ) // app2AppIPC.getLastTransaction

        } catch (e: Exception) {

            Log.e(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.getLastTransaction-> exception : ${e.message}")

            // Send the operation result
            _operationResult.value = OperationResult(isSuccess = false,
                                                     description = "Payment -> exception : ${e.message}"
                                                    )

        }

    } // suspend fun executeGetLastTransaction

    /**
     *
     * Starts the SDK's CloseAccount method.
     *
     * @param data
     *
     */
    suspend fun executeCloseAccount(data: CloseAccountData) {

        try {

            app2AppIPC.closeAccount(data, object : OperationListener {

                override fun onSuccess(response: A2ASDKResponse?) {

                    // The operation was successful.
                    Log.d(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.closeAccount-> onSuccess() : ${response}")

                    // Send the operation result
                    _operationResult.value = OperationResult(isSuccess = true,
                                                             description = "closeAccount -> onSuccess()"
                                                            )

                } // override fun onSuccess(response: A2ASDKResponse?)

                override fun onFailure(error: A2ASDKResponse?) {

                    // The operation had a negative outcome.
                    val errorMessage = formatA2AError(error)

                    Log.e(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.closeAccount -> onFailure() : ${errorMessage}")

                    // Send the operation result
                    _operationResult.value = OperationResult(isSuccess = false,
                                                             description = "closeAccount -> onFailure : ${errorMessage}"
                                                            )

                } //  override fun onFailure(error: A2ASDKResponse?) {

            } // OperationListener

            ) // app2AppIPC.getLastTransaction

        } catch (e: Exception) {

            Log.e(Constant.TAG_SOFTPOS_EVO_KOTLIN, "app2AppIPC.closeAccount-> exception : ${e.message}")

            // Send the operation result
            _operationResult.value = OperationResult(isSuccess = false,
                                                     description = "Payment -> exception : ${e.message}"
                                                    )

        }

    } // suspend fun executeCloseAccount

    /**
     *
     * Helper method that returns the AppData object
     * used during the SDK initialization phase.
     *
     */
    private fun getAppData(appId: String,
                           redirectUri: String,
                           merchantId: String,
                           merchantUsername: String,
                           deeplinkScheme: String,
                           domain: App2AppDomain
                          ): AppData {

        val appData = AppData(appId,
                              merchantId,
                              redirectUri,
                              merchantUsername,
                              deeplinkScheme,
                              domain
                             )

        return appData

    } //  private fun getAppData

} // Fine SDEKResult