source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.4'

plugin 'cocoapods-art', :sources => [
  'libs-nexi-pos-a2a-ios-release'
]


def shared_pods
  
  pod 'App2AppSDK', '1.0.3'
  pod 'Softpos', '1.0.71'
  
end

target 'sdk-ios-swiftui01-demo01' do
  use_frameworks!
  
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "16.4"
      end
    end
  end
end