package it.nexi.softpos_evo_java_light.services;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import it.nexi.softpos_evo_java_light.domain.RequestURI;

/**
 *
 * Nexi Payment
 *
 * Some functionalities must be implemented at the
 * backend level by the client.
 * References are provided as examples.
 *
 */
public final class BackendService {

    private BackendService() {

    }

    /**
     *
     * Example of the method used to receive
     * the requesturi from Nexi servers.
     *
     * Please note that the deviceId is generated by the SDK;
     * do not confuse it with the Android operating system's device ID.
     *
     */
    public static String getRequestUri(String deviceId) throws Exception {

        HttpURLConnection connection = null;

        try {

            // The backend web address.
            String strUrlBackend = "";

            URL url = new URL(strUrlBackend);

            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            connection.setRequestProperty("Accept", "application/json");
            connection.setDoInput(true);

            connection.setConnectTimeout(3000);
            connection.setReadTimeout(3000);

            int responseCode = connection.getResponseCode();

            if (responseCode == HttpURLConnection.HTTP_OK) {

                InputStream inputStream = connection.getInputStream();

                String responseJson = readStream(inputStream);

                RequestURI responseObj = SDKNexiService.gson.fromJson(responseJson, RequestURI.class);

                if (responseObj != null) {

                    return responseObj.getRequestUri();

                } else {

                    throw new Exception("Error");

                }

            } else {

                InputStream errorStream = connection.getErrorStream();

                String errorText = (errorStream != null) ? readStream(errorStream) : "unkown error";

                throw new Exception("error (" + responseCode + "): " + errorText);

            } // end if (responseCode == HttpURLConnection.HTTP_OK) {

        } catch (Exception ex) {

            throw new Exception(ex.getMessage() != null ? ex.getMessage() : "Error calling the backend");

        } finally {

            if (connection != null) {

                connection.disconnect();

            }

        }

    } // end public static String getRequestUri(String deviceId)

    /**
     *
     * Read data from input stream
     *
     */
    private static String readStream(InputStream is) throws Exception {

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(is))) {

            StringBuilder sb = new StringBuilder();

            String line;

            while ((line = reader.readLine()) != null) {

                sb.append(line);

            }

            return sb.toString();

        } // end try

    } // end private static String readStream(

}
