package it.nexi.softpos_evo_java_light.services;


import android.app.Activity;
import android.net.Uri;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;

import com.google.gson.Gson;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import it.nexi.softpos_evo_java_light.domain.Constant;
import it.nexi.softpos_evo_java_light.domain.OperationResult;
import it.nexi.softpos_evo_java_light.domain.SoftPosResponseAccountingClosure;
import it.nexi.softpos_evo_java_light.domain.SoftPosResponseLastTransaction;
import it.nexi.softpos_evo_java_light.domain.SoftPosResponsePayment;
import it.nexi.softpos_evo_java_light.domain.SoftPosResponseReversal;
import it.nexipos.app2app.App2AppIPC;
import it.nexipos.app2app.data.model.A2ASDKResponse;
import it.nexipos.app2app.data.model.AppData;
import it.nexipos.app2app.data.model.CloseAccountData;
import it.nexipos.app2app.data.model.GetLastTransactionData;
import it.nexipos.app2app.data.model.PaymentData;
import it.nexipos.app2app.data.model.ReversalData;
import it.nexipos.app2app.listener.OperationListener;
import it.nexipos.app2app.utility.App2AppDomain;
import kotlin.Unit;
import kotlin.coroutines.Continuation;
import kotlin.coroutines.CoroutineContext;
import kotlin.coroutines.EmptyCoroutineContext;

/**
 *
 * Nexi Payment
 *
 * The class provides methods for interfacing with the Nexi SDK.
 * It also allows connected activities to be notified
 * of the outcome of operations performed by the Nexi POS.
 *
 */
public class SDKNexiService {

    private SDKNexiService() {}

    // LiveData for communicating with Activities in a "lifecycle-aware" manner.
    private static final MutableLiveData<OperationResult> _operationResult = new MutableLiveData<>(null);

    // Public read-only version
    public static LiveData<OperationResult> getOperationResult() {
        return _operationResult;
    }

    // Method to reset the state
    public static void resetResult() {
        _operationResult.setValue(null);
    }

    // Nexi SDK Instance
    public static App2AppIPC app2AppIPC;

    public static final Gson gson = new Gson();

    /**
     *
     * Notifies the listening activities that the SDK
     * has provided the result of a transaction.
     *
     * @param result
     */
    public static void updateResult(OperationResult result) {

        // setValue must be called on the Main Thread.
        // If the SDK responds on a background thread, we will use postValue.
        _operationResult.postValue(result);

    }

    /**
     *
     * Starts the SDK initialization.
     * The result will be sent via the 'operationResult' LiveData.
     *
     */
    public static void initSDK(
            final Activity activity,
            final String clientId,
            final String idPuntoVendita,
            final String merchantUserName,
            final String redirectUri,
            final App2AppDomain domain,
            final String deepLinkScheme
    ) {

        ExecutorService executor = Executors.newSingleThreadExecutor();

        executor.execute(() -> {
            try {
                AppData appData = getAppData(clientId,
                                             redirectUri,
                                             idPuntoVendita,
                                             merchantUserName,
                                             deepLinkScheme,
                                             domain
                                            );

                app2AppIPC = new App2AppIPC(
                        activity,
                        appData,
                        (deviceId, onSuccessSDK, onErrorSDK) -> {
                            try {

                                // Please note that the deviceId is generated by the SDK;
                                // do not confuse it with the Android operating system's device ID.

                                // request_uri request to backend
                                String requestUri = BackendService.getRequestUri(deviceId);

                                if (requestUri != null && !requestUri.isEmpty()) {

                                    // the request_uri was returned by the backend.
                                    // The request_uri is passed to the SDK for authentication.
                                    onSuccessSDK.invoke(requestUri);

                                    // update the LiveData
                                    updateResult(new OperationResult(true, "INIT_SUCCESS_URI"));

                                } else {

                                    // The request_uri was not returned by the backend.
                                    // The SDK is notified.
                                    onErrorSDK.invoke("request_uri not found");

                                    // update the LiveData
                                    updateResult(new OperationResult(false, "Error : request_uri not found"));

                                }

                            } catch (Exception e) {

                                // An error occurred while retrieving the request_uri.
                                // The SDK is notified.
                                onErrorSDK.invoke(e.getMessage());

                                // update the LiveData
                                updateResult(new OperationResult(false, "An error occurred while retrieving the request_uri."));

                            }
                            return null;
                        },
                        connectionEvent -> {

                            // After executing the connectToRemoteService() method
                            // (see later in the code),
                            // the SDK returns the connection status.
                            switch (connectionEvent.getType()) {

                                case READY:

                                    // Notifies the connected activity that the SDK is READY.
                                    updateResult(new OperationResult(true, "READY"));
                                    break;

                                case ERROR_APP_NOT_INSTALLED:
                                case ERROR_MULTIPLE_APPS_INSTALLED:
                                case ERROR_GENERIC:

                                    // Notifies Error
                                    updateResult(new OperationResult(false, "Error SDK: " + connectionEvent.getType()));
                                    break;

                                case CONNECTED :

                                    // Notifies the connected activity that the SDK is CONNECTED but not READY
                                    updateResult(new OperationResult(false, "CONNECTED but not READY: " + connectionEvent.getType()));
                                    break;

                                case DISCONNECTED:

                                    // Notifies the connected activity that the SDK is disconnected
                                    updateResult(new OperationResult(false, "Service disconnected"));
                                    break;

                                default :

                                    // unhandled event

                                    // Notifies the connected activity that the SDK
                                    updateResult(new OperationResult(false, "nhandled event"));
                                    break;

                            } // switch(connectionEvent.getType())

                            return null;

                        } // connectionEvent -> {

                ); // app2AppIPC = new App2AppIPC(

                // starts the connection with the SDK.
                // The outcome of the operation can be checked in the ConnectionEvent.
                app2AppIPC.connectToRemoteService();

            } catch (Exception ex) {

                updateResult(new OperationResult(false, "Fatal error : " + ex.getMessage()));

            }

        }); // executor.execute(()

    } // end initSDK


    /**
     *
     * Starts the SDK's Payment method.
     *
     * @param data
     *
     */
    public static void executePay(PaymentData data) {
        try {

            // The operation is performed in a separate thread.
            new Thread(() -> {
                try {

                    app2AppIPC.pay(data, new OperationListener() {
                        @Override
                        public void onSuccess(A2ASDKResponse response) {

                            // The operation was successful.
                            Log.d(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.pay -> onSuccess() : " + response);

                            // Send the operation result via LiveData (postValue is thread-safe).
                            updateResult(new OperationResult(true, "Payment -> onSuccess()"));

                        } // public void onSuccess(

                        @Override
                        public void onFailure(A2ASDKResponse error) {

                            // The operation had a negative outcome.
                            String errorMessage = Utils.formatA2AError(error);

                            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.pay -> onFailure() : " + errorMessage);

                            // Send the operation result via LiveData (postValue is thread-safe).
                            updateResult(new OperationResult(false, "Payment -> onFailure : " + errorMessage));

                        } //  public void onFailure(

                    }, new Continuation<Unit>() {

                        // Implementation required to call a suspend function from Java
                        @NonNull
                        @Override
                        public CoroutineContext getContext() {
                            return EmptyCoroutineContext.INSTANCE;
                        }

                        @Override
                        public void resumeWith(@NonNull Object o) {

                            // This method is called upon completion of the coroutine.
                            Log.d(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.pay -> resumeWith()");

                        }

                    });

                } catch (Exception e) {

                    Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.pay -> exception " + e.getMessage());

                    // Send the operation result via LiveData (postValue is thread-safe).
                    updateResult(new OperationResult(false, "Payment -> exception : " + e.getMessage()));

                }

            }).start();

        } catch (Exception e) {

            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.pay -> exception: " + e.getMessage());

            // Send the operation result via LiveData (postValue is thread-safe).
            updateResult(new OperationResult(false, "Payment -> exception : " + e.getMessage()));

        }

    } // end executePay

    /**
     *
     * Starts the SDK's Revert method.
     *
     * @param data
     *
     */
    public static void executeRevert(final ReversalData data) {

        // The operation is performed in a separate thread.
        try {

            new Thread(() -> {

                try {

                    app2AppIPC.revert(data, new OperationListener() {
                        @Override
                        public void onSuccess(A2ASDKResponse response) {

                            // The operation was successful.
                            Log.d(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.revert -> onSuccess() : " + response);

                            // Send the operation result via LiveData (postValue is thread-safe).
                            updateResult(new OperationResult(true, "Revert -> onSuccess()"));
                        }

                        @Override
                        public void onFailure(A2ASDKResponse error) {

                            // The operation had a negative outcome.
                            String errorMessage = Utils.formatA2AError(error);

                            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.revert -> onFailure() : " + errorMessage);

                            // Send the operation result via LiveData (postValue is thread-safe).
                            updateResult(new OperationResult(false, "Revert -> onFailure : " + errorMessage));

                        }

                    }, new Continuation<Unit>() {

                        // Implementation required to call a suspend function from Java
                        @NonNull
                        @Override
                        public CoroutineContext getContext() {

                            return EmptyCoroutineContext.INSTANCE;

                        }

                        @Override
                        public void resumeWith(@NonNull Object o) {

                            // This method is called upon completion of the coroutine.
                            Log.d(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.revert -> resumeWith()");
                        }

                    });

                } catch (Exception e) {

                    Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.revert -> exception interna: " + e.getMessage());

                    // Send the operation result via LiveData (postValue is thread-safe).
                    updateResult(new OperationResult(false, "Revert -> exception : " + e.getMessage()));

                }

            }).start();

        } catch (Exception e) {

            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.revert -> exception: " + e.getMessage());

            // Send the operation result via LiveData (postValue is thread-safe).
            updateResult(new OperationResult(false, "Revert -> exception : " + e.getMessage()));

        }

    } // end executeRevert

    /**
     *
     * Starts the SDK's GetLastTransaction method.
     *
     * @param data
     *
     */
    public static void executeGetLastTransaction(final GetLastTransactionData data) {

        // The operation is performed in a separate thread.
        try {

            new Thread(() -> {

                try {

                    app2AppIPC.getLastTransaction(data, new OperationListener() {
                        @Override
                        public void onSuccess(A2ASDKResponse response) {

                            // The operation was successful.
                            Log.d(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.getLastTransaction -> onSuccess() : " + response);

                            // Send the operation result via LiveData (postValue is thread-safe).
                            updateResult(new OperationResult(true, "GetLastTransaction -> onSuccess()"));

                        }

                        @Override
                        public void onFailure(A2ASDKResponse error) {

                            // The operation had a negative outcome.
                            String errorMessage = Utils.formatA2AError(error);

                            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.getLastTransaction -> onFailure() : " + errorMessage);

                            // Send the operation result via LiveData (postValue is thread-safe).
                            updateResult(new OperationResult(false, "GetLastTransaction -> onFailure : " + errorMessage));

                        }

                    }, new Continuation<Unit>() {

                        // Implementation required to call a suspend function from Java
                        @NonNull
                        @Override
                        public CoroutineContext getContext() {

                            return EmptyCoroutineContext.INSTANCE;

                        }

                        @Override
                        public void resumeWith(@NonNull Object o) {

                            // This method is called upon completion of the coroutine.
                            Log.d(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.getLastTransaction -> resumeWith()");

                        }

                    });

                } catch (Exception e) {

                    Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.getLastTransaction -> exception interna: " + e.getMessage());

                    // Send the operation result via LiveData (postValue is thread-safe).
                    updateResult(new OperationResult(false, "GetLastTransaction -> exception : " + e.getMessage()));

                }

            }).start();

        } catch (Exception e) {

            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.getLastTransaction -> exception: " + e.getMessage());

            // Send the operation result via LiveData (postValue is thread-safe).
            updateResult(new OperationResult(false, "GetLastTransaction -> exception : " + e.getMessage()));

        }

    } // end executeGetLastTransaction

    /**
     *
     * Starts the SDK's CloseAccount method.
     *
     * @param data
     *
     */
    public static void executeCloseAccount(final CloseAccountData data) {

        // The operation is performed in a separate thread.
        try {

            new Thread(() -> {
                try {

                    app2AppIPC.closeAccount(data, new OperationListener() {
                        @Override
                        public void onSuccess(A2ASDKResponse response) {

                            // The operation was successful.
                            Log.d(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.closeAccount -> onSuccess() : " + response);

                            // Send the operation result via LiveData (postValue is thread-safe).
                            updateResult(new OperationResult(true, "closeAccount -> onSuccess()"));

                        }

                        @Override
                        public void onFailure(A2ASDKResponse error) {

                            // The operation had a negative outcome.
                            String errorMessage = Utils.formatA2AError(error);

                            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.closeAccount -> onFailure() : " + errorMessage);

                            // Send the operation result via LiveData (postValue is thread-safe).
                            updateResult(new OperationResult(false, "closeAccount -> onFailure : " + errorMessage));

                        }

                    }, new Continuation<Unit>() {

                        // Implementation required to call a suspend function from Java
                        @NonNull
                        @Override
                        public CoroutineContext getContext() {

                            return EmptyCoroutineContext.INSTANCE;

                        }

                        @Override
                        public void resumeWith(@NonNull Object o) {

                            // This method is called upon completion of the coroutine.
                            Log.d(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.closeAccount -> resumeWith()");

                        }

                    });

                } catch (Exception e) {

                    Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.closeAccount -> exception interna: " + e.getMessage());

                    // Send the operation result via LiveData (postValue is thread-safe).
                    updateResult(new OperationResult(false, "closeAccount -> exception : " + e.getMessage()));

                }

            }).start();

        } catch (Exception e) {

            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, "app2AppIPC.closeAccount -> exception: " + e.getMessage());

            // Send the operation result via LiveData (postValue is thread-safe).
            updateResult(new OperationResult(false, "closeAccount -> exception : " + e.getMessage()));

        }

    } // end executeCloseAccount

    /**
     *
     * Helper method that returns the AppData object
     * used during the SDK initialization phase.
     *
     */
    private static AppData getAppData(String appId,
                                      String redirectUri,
                                      String merchantId,
                                      String merchantUsername,
                                      String deeplinkScheme,
                                      App2AppDomain domain) {


        return new AppData(appId,
                           merchantId,
                           redirectUri,
                           merchantUsername,
                           deeplinkScheme,
                           domain
                          );

    } // end getAppData

    /**
     *
     * Parses the response sent by Nexi POS and returns
     * an object containing the transaction data executed
     *
     * @param data
     *
     * @return
     *
     */
    public static SoftPosResponsePayment parseSoftPosResponsePayment(Uri data){

        SoftPosResponsePayment softPosResponsePayment = null;

        try {

            if (data != null){

                softPosResponsePayment = new SoftPosResponsePayment();

                softPosResponsePayment.setCallerTrxId(data.getQueryParameter("callerTrxId"));
                softPosResponsePayment.setOperationType(data.getQueryParameter("operationType"));
                softPosResponsePayment.setResult(data.getQueryParameter("result"));
                softPosResponsePayment.setAmount(data.getQueryParameter("amount"));
                softPosResponsePayment.setTipAmount(data.getQueryParameter("tipAmount"));
                softPosResponsePayment.setTotalAmount(data.getQueryParameter("totalAmount"));
                softPosResponsePayment.setActionCode(data.getQueryParameter("actionCode"));
                softPosResponsePayment.setPan(data.getQueryParameter("pan"));
                softPosResponsePayment.setTransactionType(data.getQueryParameter("transactionType"));
                softPosResponsePayment.setAuthorizationNumber(data.getQueryParameter("authorizationNumber"));
                softPosResponsePayment.setTimeStamp(data.getQueryParameter("timestamp"));
                softPosResponsePayment.setResultDescription(data.getQueryParameter("resultDescription"));
                softPosResponsePayment.setCardTypeCVM(data.getQueryParameter("cardTypeCVM"));
                softPosResponsePayment.setAcquireId(data.getQueryParameter("acquirerId"));
                softPosResponsePayment.setStan(data.getQueryParameter("stan"));
                softPosResponsePayment.setOperationNumber(data.getQueryParameter("operationNumber"));
                softPosResponsePayment.setAcquirerName(data.getQueryParameter("acquirerName"));
                softPosResponsePayment.setTerminalID(data.getQueryParameter("terminalId"));
                softPosResponsePayment.setMerchantId(data.getQueryParameter("merchantId"));
                softPosResponsePayment.setUrlTicket(data.getQueryParameter("urlTicket"));
                softPosResponsePayment.setAutoClose(data.getQueryParameter("autoClose"));
                String campiAggiuntivi = data.getQueryParameter("CT122");

                if (campiAggiuntivi != null && !campiAggiuntivi.isEmpty()) {
                    campiAggiuntivi.replace("%7C","|");
                }

                softPosResponsePayment.setCampiAggiuntivi(data.getQueryParameter("CT122"));

            }

        } catch (Exception ex){

            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, ex.getMessage());

        }

        return softPosResponsePayment;

    } // end public static SoftPosResponsePayment parseSoftPosResponsePayment(Uri data)

    /**
     *
     * Parses the response sent by Nexi POS and returns
     * an object containing the transaction data executed
     *
     * @param data
     *
     * @return
     *
     */
    public static SoftPosResponseReversal parseSoftPosResponseReversal(Uri data){

        SoftPosResponseReversal softPosResponseReversal = null;

        try {

            if (data != null){

                softPosResponseReversal = new SoftPosResponseReversal();

                softPosResponseReversal.setCallerTrxId(data.getQueryParameter("callerTrxId"));
                softPosResponseReversal.setOperationType(data.getQueryParameter("operationType"));
                softPosResponseReversal.setResult(data.getQueryParameter("result"));
                softPosResponseReversal.setHostTotal(data.getQueryParameter("hostTotal"));
                softPosResponseReversal.setTerminalTotal(data.getQueryParameter("terminalTotal"));

            }

        } catch (Exception ex){

            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, ex.getMessage());

        }

        return softPosResponseReversal;

    } // end public static SoftPosResponseReversal parseSoftPosResponseReversal(Uri data)

    /**
     *
     * Parses the response sent by Nexi POS and returns
     * an object containing the transaction data executed
     *
     * @param data
     *
     * @return
     */
    public static SoftPosResponseLastTransaction parseSoftPosResponseGetLastTransaction(Uri data){

        SoftPosResponseLastTransaction softPosResponseLastTransaction = null;

        try {

            if (data != null){

                softPosResponseLastTransaction = new SoftPosResponseLastTransaction();

                softPosResponseLastTransaction.setResult(data.getQueryParameter("result"));
                softPosResponseLastTransaction.setCallerTrxId(data.getQueryParameter("callerTrxId"));
                softPosResponseLastTransaction.setAmount(data.getQueryParameter("amount"));
                softPosResponseLastTransaction.setTipAmount(data.getQueryParameter("tipAmount"));
                softPosResponseLastTransaction.setTotalAmount(data.getQueryParameter("totalAmount"));
                softPosResponseLastTransaction.setOperationType(data.getQueryParameter("operationType"));
                softPosResponseLastTransaction.setTerminalType(data.getQueryParameter("terminalType"));
                softPosResponseLastTransaction.setTerminalID(data.getQueryParameter("f41"));

                String campiAggiuntiviCT122         = data.getQueryParameter("CT122");
                String campiAggiuntiviATAGSRECEIPT  = data.getQueryParameter("ATAGSRECEIPT");

                if (campiAggiuntiviCT122 != null && !campiAggiuntiviCT122.isEmpty()) {
                    campiAggiuntiviCT122.replace("%7C","|");

                    softPosResponseLastTransaction.setCampiAggiuntiviCT122(campiAggiuntiviCT122);
                }

                if (campiAggiuntiviATAGSRECEIPT != null && !campiAggiuntiviATAGSRECEIPT.isEmpty()) {
                    campiAggiuntiviCT122.replace("%7C","|");

                    softPosResponseLastTransaction.setCampiAggiuntiviATAGSRECEIPT(campiAggiuntiviATAGSRECEIPT);

                }

            } //  if (data != null){

        } catch (Exception ex){

            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, ex.getMessage());

        }

        return softPosResponseLastTransaction;

    } //  end public static SoftPosResponseLastTransaction parseSoftPosResponseGetLastTransaction(Uri data)

    /**
     *
     * Parses the response sent by Nexi POS and returns
     * an object containing the transaction data executed
     *
     * @param data
     *
     * @return
     *
     */
    public static SoftPosResponseAccountingClosure parseSoftPosResponseAccountingClosure(Uri data){

        SoftPosResponseAccountingClosure softPosResponseAccountingClosure = null;

        try {

            if (data != null){

                softPosResponseAccountingClosure = new SoftPosResponseAccountingClosure();

                softPosResponseAccountingClosure.setResult(data.getQueryParameter("result"));
                softPosResponseAccountingClosure.setCallerTrxId(data.getQueryParameter("callerTrxId"));
                softPosResponseAccountingClosure.setHostTotal(data.getQueryParameter("hostTotal"));
                softPosResponseAccountingClosure.setTerminalTotal(data.getQueryParameter("terminalTotal"));

            } // if (data != null)

        } catch (Exception ex){

            Log.e(Constant.TAG_SOFTPOS_EVO_JAVA, ex.getMessage());

        }

        return softPosResponseAccountingClosure;

    } //  end public static SoftPosResponseAccountingClosure parseSoftPosResponseAccountingClosure(Uri data)

} // end class
