spring.application.name=softpos-backend-evolution-java
### confugurazioni Environment
spring.profiles.active=@activatedProperties@
### confugurazioni Tomcat Embedded di testSoftPosB2B
server.port=8081
server.servlet.context-path=/softpos-backend-evolution
security.basic.enabled=false
## Version Web Service
ws.version=1.0.0
